services:
  db:
    image: postgres:15.2
    healthcheck:
      test: ["CMD", "pg_isready", "--username=postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgrespassword
      POSTGRES_DB: kanban_dev
      PGDATA: /var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    secrets:
      - postgrespassword

  web:
    image: ${WEB_IMAGE:-ghcr.io/imeraj/kanban:latest}
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 30s
        max_attempts: ${MAX_ATTEMPTS:-0}
      update_config:
        parallelism: 1
        order: start-first
        delay: 5s
        failure_action: rollback
      rollback_config:
        parallelism: 0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000"]
      interval: 5s
      timeout: 3s
      retries: 3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DATABASE_URL_FILE: /run/secrets/databaseurl
      SECRET_KEY_BASE_FILE: /run/secrets/secretkeybase
      PHX_HOST: "localhost"
    ports:
      - 4000:4000
    depends_on:
      - db
    command: >
      bash -c "bin/migrate && bin/server"
    secrets:
      - databaseurl
      - secretkeybase
  loki:
    image: grafana/loki:2.9.3
    configs:
      - source: loki
        target: /etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:latest
    environment:
      - DOCKER_API_VERSION=1.44
    deploy:
      mode: global
    configs:
      - source: promtail
        target: /etc/promtail/config.yml
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  grafana:
    image: grafana/grafana:9.5.15
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    ports:
      - "3000:3000"
    configs:
      - source: grafana_datasources
        target: /etc/grafana/provisioning/datasources/datasource.yml
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  grafana-storage:
  db_data:

configs:
  loki:
    file: ./instrumentation/loki/local.yaml
  promtail:
    file: ./instrumentation/promtail/${PROMTAIL_CONFIG-swarm}.yaml
  grafana_datasources:
    file: ./instrumentation/grafana/datasources/datasources.yaml

secrets:
  postgrespassword:
    file: ./secrets/.postgrespassword
  secretkeybase:
    file: ./secrets/.secretkeybase
  databaseurl:
    file: ./secrets/.databaseurl
